### PR TITLE
Added support for SerializationName/SerlizeIgnore/Property annotations.

### PR DESCRIPTION
**Pull request by Zalastax**
@SerializedName("to","from") x;
@SerializedToName("toAndFrom") y;
@SerializedToName("to") @SerializedFromName("from") z;
@SerializedToName("to") w;
Should all work.  

Please run dfmt on painlessjson. I tried but it wanted to modify the whole file for me.

### CODE REVIEW

**Comment by Zalastax** [comment]
Added support for @property.

**Comment by BlackEdder** [comment]
Nice work. Will look at it over the weekend. 

When you say:

``` D
@SerializedToName("toAndFrom") y;
```

Did you mean:

``` D
 @SerializedName("toAndFrom") y;
```

About dfmt. Think that at the moment it does not support in place fixing (which is weird because dfix from the same author does exactly that). So the only solution is to run it, pipe it to a separate file and then replace the original file. I'd be happy to do that after merging.

**Comment by Zalastax** [comment]
Yeah I meant:

```
@SerializedName("toAndFrom") y;
```

**Comment by Zalastax** [comment]
I'm not sure if the  serializationFromName and serializationToName functions should be in the annotations module but I think they fitted best there. Maybe a new module instead but I don't want module bloat.

**Comment by BlackEdder** [comment]
Thanks, looks great.

**Pull request merged**
