### PR TITLE
Use template constraints instead of static if in fromJSON and toJSON.

### PR DESCRIPTION
**Pull request by Zalastax**
I saw this in jsonizer and think it's a good idiom.
It makes sure that there are no ambiguities for the caller, and the code is easier to analyze.

### CODE REVIEW

**Comment by BlackEdder** [comment]
A quick question before merging. Could you check whether dub -b docs still gives a reasonable output.

**Comment by Zalastax** [comment]
There is a problem in the output. The doc makes it look like the method is constrained, even though it is just an implementation detail.

```
T fromJSON(T)(JSONValue json) if (!isBuiltinType!T && !is(T == JSONValue));
Convert from JSONValue to any other type

Examples:
    Converting common types

    assert(fromJSON!int(JSONValue(1)) == 1);
    assert(fromJSON!double(JSONValue(1.0)) == 1);
    assert(fromJSON!double(JSONValue(1.3)) == 1.3);
    assert(fromJSON!string(JSONValue("str")) == "str");
    assert(fromJSON!bool(JSONValue(true)) == true);
    assert(fromJSON!bool(JSONValue(false)) == false);
    assert(fromJSON!JSONValue(JSONValue(true)) == JSONValue(true));
```

This is not ideal. Is an acceptable solution to have fromJSON!T as a front that forwards to the implementation? I would prefer some ddoc magic instead if it's possible.

**Comment by BlackEdder** [comment]
I think something like the following (at the top?) might work:

``` D
version(D_Ddoc) 
{
/// Convert from JSONValue to any other type
  T fromJSON(T)(JSONValue json)
  { return T; }
} 
else 
{
 ... current conditional implementation...
}
```

**Comment by Zalastax** [comment]
That works, but there is a bug in DDoc that makes it not print the examples. Placing the example code above the function solves this, but then the example output is above the function.  

When i think about it I would prefer to have toJSON as just a wrapper to something like serialize!JSONSerializer. This is how vibe.d does this.  
We could start working towards that by first making fromJSON!T a function that forwards to the implementation and later refactor into a strategy pattern.

**Comment by BlackEdder** [comment]
I think making the serialization more independent from toJSON would be great. Would you still like me to merge this or prefer to wait?

Did you put the unittests/examples outside the version block or inside it? Examples before function is not too big an issue.

**Comment by Zalastax** [comment]
I put them outside both version blocks. I will do a small update where I use a toJSON/fromJSON function that forwards to private implementation functions. So wait with merging this pull request until that.

**Comment by Zalastax** [comment]
I'm happy with this. It's a step in the right direction. The facade will be needed later anyway.

**Comment by BlackEdder** [comment]
Thanks :+1:

**Pull request merged**
