### PR TITLE
Automatic camelCase conversion

### PR DESCRIPTION
**Pull request by Zalastax**
Resolves issue #33.
I have added an option object that can be used to turn this feature on or off. It might be better to move all the functions to an object, but have free functions that make the call using the default-object.

### CODE REVIEW

**Comment by BlackEdder** [comment]
This looks good. I am now just wondering if it would be wise to add loads of switches to the conversion. Maybe it would be easier to add simple helper functions to turn JSONValue representation of a class/struct from/to camelCase. That way the user can always convert the JSON after/before calling toJSON/fromJSON? Might keep it more maintainable than adding special cases/switches.

**Comment by Zalastax** [comment]
I don't like the idea of having to transform the data before passing it in. That's a step that will be forgotten somewhere. 
My reasoning for a configuration object is that you might want a certain default for your whole application. If I want camelCase to underscore everywhere I should only have to say that once. If I have one place where I don't want it I should be able to say that as well (using annotations, or modifying the option object for that place).  
So I would prefer if we make changes to support:
- If I don't want configuration I just import painlessjson
- If I want a global configuration I can make my own package that imports painlessjson and exports it using my new default values.
- I can override the default-configuration anywhere
- I can take the default-configuration and change only one variable.
- I can override the configuration an object has. If I want to change the name of a specific field I would prefer if it was possible.

The current solution only solves the override anywhere problem elegantly, but it could be modified to fit the other problems as well.

**Comment by Zalastax** [comment]
Any more input to this? What should be done to merge this pull request? How should configurability be approached?

**Comment by BlackEdder** [comment]
Sorry about the delay. Just started new job, so been bit distracted.

**Pull request merged**
