### PR TITLE
Fixes I made to my version

### PR DESCRIPTION
**Pull request by Zalastax**
toJSON will just return the value if it's passed a JSONValue. If fromJSON is trying to convert to JSONValue it will just return the value passed. This is to make template programming using painlessjson easier.
I added support for classes without default-constructor or private fields if they use the helper-functions _fromJSON and/or to_JSON.

### CODE REVIEW

**Comment by BlackEdder** [comment]
Merged, thank you!

Development on this has mostly been stalled. Partly because I realized classes would be more difficult to handle (which you now solved :) ), partly because I focused on different project and partly because there was talk of implementing similar functionality into phobos. Still it would be worth while to keep this alive.

Would you be interested in getting commit rights on this repo? I'll add it to code.dlang.org as well in the next couple of days.

**Comment by Zalastax** [comment]
I don't know what to improve right now. It's exactly what I need for my purposes for the moment. The usage is simple and the setup is really easy.
I will push to my own repo if I find anything more to improve and make a pull request. In that way I have some code review before pusing it to the main repo.

**Comment by BlackEdder** [comment]
Looking forward to your pull requests :)

Over the next couple of days I will try to flesh out the README/documentation, tag version (maybe even 1.0.0 if we think it is mostly complete for what it tries to do) and then add it to code.dlang.org.

**Comment by Zalastax** [comment]
Great!
Do you see anything that needs to be improved?
Should I add that it looks for @property? Perhaps stop hardcoding _toJSON and _fromJSON and use http://dlang.org/attribute.html#uda instead?

**Comment by BlackEdder** [comment]
I think I prefer _toJSON and _fromJSON over using attributes. People tend to be a bit wary of using attributes too often. It would be cool though to add a @NoJSON property to indicate that a certain field should not be converted to/from JSON (similar to cereal, see bottom of this message)

By the way. Instead of using _toJSON/_fromJSON would it not be possible for a class to just define toJSON/fromJSON (without the underscore) and then that will automatically be used instead. Is there a reason to add the extra layer of redirection?

EDIT: Handling @property in an intelligent way would be very useful. Although not completely sure what the best default way would be. I guess it would treat it as a normal member variable (what if there is a reader property, but no writer)? I wonder what/if cereal handles @property specifically.

(The following are all pie in the sky ideas that are low priority but might be cool)
In general I am not sure how well painlessjson deals with certain corner cases (templates/derived classes/static classes/arrays). What painless JSON does is (de)serialize structs and classes and then outputting JSON. It might be interesting to look at https://github.com/atilaneves/cerealed/tree/master/cerealed and see how they handle corner cases, because that is a more advanced (de)serializer. Maybe copy parts of their "API" like the @NoCereal attribute (@NoJSON), accept and postBlit?. It might even be possible to use cereal and build painlessjson on top.

**Comment by BlackEdder** [comment]
Sorry just thinking out loud here. Splitting the (de)serializing part from the toJSON/fromJSON part could be interesting/helpful

One thing that cereal does is give you easy access to the default implementation from your custom implementation, so you can override bits. I guess we can already do the same by:

```
class A {
  int a = 1;
  int b = 2;
  JSONValue toJSON() {
    auto json = painlessjson.toJSON( this )
    if (a == 1)
      ( json["a"] = 5.toJSON
    return json;
  }
}
```

**Pull request merged**
