### PR TITLE
Use const

### PR DESCRIPTION
**Pull request by Zalastax**
Just convert all our functions to use const instead. It's a nice contract to have.

### CODE REVIEW

**Comment by BlackEdder** [comment]
Good idea. Although isn't using in preferred over const? Not really sure though?

**Comment by Zalastax** [comment]
Yes. I looked it up in http://ddili.org/ders/d.en/function_parameters.html and you seem to be right. Will do a quick fix. It might even remove the problem with toPrettyString.

**Comment by Zalastax** [comment]
I checked on DPaste and it seems like toPrettyString isn't callable using in on older versions. I don't really know the difference between in and const but in seems to be more clear.

**Comment by BlackEdder** [comment]
Merged +1

About in versus const. I do remember at some point reading that _in_ is slightly more general than const, but I can't remember why this was. For me _in_ more clearly "communicates" that it will happily take any argument whether not const, const or immutable.

**Pull request merged**
